---
- name: Configuration deployment with CVP
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Provision CVP with AVD configuration
      import_role:
        name: eos_config_deploy_eapi
