---
- name: "Run Fabric states validation"
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:

    - name: Deploy configuration to device
      import_role:
        name: eos_validate_state
